"use client";
import { useQuery } from "@tanstack/react-query";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { ArrowUpRight, Clock3, DollarSign, PhoneCall, Sparkles, Target, Users } from "lucide-react";
import { api } from "@/lib/api";
import { duration, date } from "@/lib/utils";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/page-header";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";

export function DashboardView(){const {data,isLoading,error}=useQuery({queryKey:["dashboard"],queryFn:api.dashboard});
 if(isLoading)return <div className="space-y-5"><Skeleton className="h-20"/><div className="grid gap-4 md:grid-cols-3"><Skeleton className="h-32"/><Skeleton className="h-32"/><Skeleton className="h-32"/></div><Skeleton className="h-80"/></div>;
 if(error||!data)return <Card className="p-6 text-rose-300">Could not reach the voice-agent backend. Check NEXT_PUBLIC_API_URL and make sure FastAPI is running.</Card>;
 const grouped=new Map<string,number>(); data.calls.forEach(c=>{const key=new Date(c.started_at).toLocaleDateString("en",{month:"short",day:"numeric"});grouped.set(key,(grouped.get(key)||0)+1)});const chart=Array.from(grouped).map(([name,calls])=>({name,calls}));
 const stats=[{label:"Total calls",value:data.total_calls,detail:`${data.calls_today} today`,icon:PhoneCall},{label:"Active now",value:data.active_calls,detail:"Live voice sessions",icon:Sparkles},{label:"Conversion",value:`${data.conversion_rate}%`,detail:"Captured-field rate",icon:Target},{label:"Avg. duration",value:duration(data.average_duration),detail:"Across completed calls",icon:Clock3},{label:"Leads engaged",value:new Set(data.calls.map(c=>c.to_number||c.from_number)).size,detail:"Unique contacts",icon:Users},{label:"Revenue",value:"—",detail:"Connect billing source",icon:DollarSign}];
 return <><PageHeader eyebrow="Command center" title="Good evening, operator." description="A live view of every conversation, signal, and outcome across your voice workforce." actions={<button className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs">Last 30 days <ArrowUpRight size={14}/></button>}/>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{stats.map(({label,value,detail,icon:Icon})=><Card key={label} className="group relative overflow-hidden p-4 xl:col-span-1"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-violet-400/40 to-transparent opacity-0 transition group-hover:opacity-100"/><div className="flex items-center justify-between text-zinc-500"><span className="text-xs">{label}</span><Icon size={14}/></div><div className="mt-4 text-2xl font-semibold tracking-tight tabular">{value}</div><div className="mt-1 text-[10px] text-zinc-600">{detail}</div></Card>)}</div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.65fr_1fr]"><Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-medium">Call momentum</h2><p className="mt-1 text-xs text-zinc-600">Completed sessions over time</p></div><Badge tone="purple">Live data</Badge></div><div className="mt-7 h-64">{chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="calls" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8b5cf6" stopOpacity={.4}/><stop offset="100%" stopColor="#8b5cf6" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.04)" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:"#52525b",fontSize:10}}/><Tooltip contentStyle={{background:"#15161d",border:"1px solid rgba(255,255,255,.08)",borderRadius:12,fontSize:12}}/><Area type="monotone" dataKey="calls" stroke="#8b5cf6" strokeWidth={2} fill="url(#calls)"/></AreaChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-xs text-zinc-600">Your first completed call will start this graph.</div>}</div></Card>
 <Card className="p-5"><h2 className="text-sm font-medium">Recent signal</h2><p className="mt-1 text-xs text-zinc-600">Latest testing activity</p><div className="mt-5 space-y-1">{data.calls.slice(0,6).map(call=><a href={`/conversations/${call.id}`} key={call.call_sid} className="flex items-center gap-3 rounded-xl p-2.5 transition hover:bg-white/[.04]"><span className="grid size-8 place-items-center rounded-xl bg-violet-500/10 text-violet-300"><PhoneCall size={14}/></span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-medium">{call.niche.replace("_"," ")} · {call.direction}</span><span className="block truncate text-[10px] text-zinc-600">{date(call.started_at)}</span></span><span className="text-[10px] tabular text-zinc-500">{duration(call.duration_seconds)}</span></a>)}{!data.calls.length&&<p className="py-16 text-center text-xs text-zinc-600">No completed test calls yet.</p>}</div></Card></div></>}
